name: Python Snake Game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install virtual display (Xvfb)
      run: sudo apt-get install -y xvfb

    - name: Run Snake Game with virtual display
      run: |
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99
        python main.py
