name: Snake Game on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-game:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run Snake Game (10 seconds)
      run: |
        start /B python "Snake Game.py"
        timeout /T 10
        taskkill /IM python.exe /F
